### PR TITLE
#32 Boxes for semantic features are obviously wrong 

### PR DESCRIPTION
**Pull request by apattnaik0721013**
@paul-michalik 
#32 is fixed in this branch.
1. Added std::vector<cv::Rect> mRoiList to frame which hold semantic rectangle for that frame.
2. this mRoiList is used to draw semantic rectangle.
3. remove semantic frame information as it is handled in separate issue.

### CODE REVIEW

**Comment by paul-michalik** [comment]
@apattnaik0721013 I do not now which issue this belongs to. Please rename the branch such that it is obvious which issue is involved here. Is it #32? Then call it `bugfix/32-boxes-for-semantic-features`. The rule is: <issue#>-<first 25-30 characters from the title with spaces replaced by dashes>. Please do this for all your branches which are related to GitHub issues. For Jira issues we use the convention from Atlassian!

**Comment by paul-michalik** [comment]
1. Start the x86 version of the program on Windows and wait until the tracing starts
2. Click into the map viewer or try to grab it with a mouse
3. A Windows system exception is thrown, consistently on the same location:

capture

Stack corruption is the sign that the program has corrupted memory in a very thorough way. Please verify and try to fix.

```
>	pangolin.dll!pangolin::Handler3D::GetPosNormal(pangolin::View & view, int winx, int winy, double * p, double * Pw, double * Pc, double * nw, double default_z) Line 185	C++	Symbols loaded.
 	pangolin.dll!pangolin::Handler3D::Mouse(pangolin::View & display, pangolin::MouseButton button, int x, int y, bool pressed, int button_state) Line 198	C++	Symbols loaded.
 	pangolin.dll!pangolin::Handler::Mouse(pangolin::View & d, pangolin::MouseButton button, int x, int y, bool pressed, int button_state) Line 56	C++	Symbols loaded.
 	pangolin.dll!pangolin::process::Mouse(int button_raw, int state, int x, int y) Line 482	C++	Symbols loaded.
 	pangolin.dll!pangolin::WinWindow::HandleWinMessages(unsigned int message, unsigned int wParam, long lParam) Line 317	C++	Symbols loaded.
 	pangolin.dll!pangolin::WinWindow::WndProc(HWND__ * hwnd, unsigned int uMsg, unsigned int wParam, long lParam) Line 238	C++	Symbols loaded.
 	user32.dll!_InternalCallWinProc@20()	Unknown	Symbols loaded.
 	user32.dll!_UserCallWinProcCheckWow@32()	Unknown	Symbols loaded.
 	user32.dll!_CallWindowProcAorW@24()	Unknown	Symbols loaded.
 	user32.dll!_CallWindowProcW@20()	Unknown	Symbols loaded.
 	opengl32.dll!_wglWndProc@16()	Unknown	Symbols loaded.
 	user32.dll!_InternalCallWinProc@20()	Unknown	Symbols loaded.
 	user32.dll!_UserCallWinProcCheckWow@32()	Unknown	Symbols loaded.
 	user32.dll!_DispatchMessageWorker@8()	Unknown	Symbols loaded.
 	user32.dll!_DispatchMessageA@4()	Unknown	Symbols loaded.
 	opencv_highgui331d.dll!cvWaitKey(int delay) Line 2013	C++	Symbols loaded.
 	opencv_highgui331d.dll!cv::waitKeyEx(int delay) Line 220	C++	Symbols loaded.
 	opencv_highgui331d.dll!cv::waitKey(int delay) Line 226	C++	Symbols loaded.
 	semantic_monocular.exe!ORB_SLAM2::Viewer::Run() Line 139	C++	Symbols loaded.
 	semantic_monocular.exe!std::_Invoker_pmf_pointer::_Call<void (__thiscall ORB_SLAM2::Viewer::*)(void),ORB_SLAM2::Viewer *>(void(ORB_SLAM2::Viewer::*)() _Pmf, ORB_SLAM2::Viewer * && _Arg1) Line 1790	C++	Symbols loaded.
 	semantic_monocular.exe!std::invoke<void (__thiscall ORB_SLAM2::Viewer::*)(void),ORB_SLAM2::Viewer *>(void(ORB_SLAM2::Viewer::*)() && _Obj, ORB_SLAM2::Viewer * && <_Args_0>) Line 1790	C++	Symbols loaded.
 	semantic_monocular.exe!std::_LaunchPad<std::unique_ptr<std::tuple<void (__thiscall ORB_SLAM2::Viewer::*)(void),ORB_SLAM2::Viewer *>,std::default_delete<std::tuple<void (__thiscall ORB_SLAM2::Viewer::*)(void),ORB_SLAM2::Viewer *> > > >::_Execute<0,1>(std::tuple<void (__thiscall ORB_SLAM2::Viewer::*)(void),ORB_SLAM2::Viewer *> & _Tup, std::integer_sequence<unsigned int,0,1> __formal) Line 240	C++	Symbols loaded.
 	semantic_monocular.exe!std::_LaunchPad<std::unique_ptr<std::tuple<void (__thiscall ORB_SLAM2::Viewer::*)(void),ORB_SLAM2::Viewer *>,std::default_delete<std::tuple<void (__thiscall ORB_SLAM2::Viewer::*)(void),ORB_SLAM2::Viewer *> > > >::_Run(std::_LaunchPad<std::unique_ptr<std::tuple<void (__thiscall ORB_SLAM2::Viewer::*)(void),ORB_SLAM2::Viewer *>,std::default_delete<std::tuple<void (__thiscall ORB_SLAM2::Viewer::*)(void),ORB_SLAM2::Viewer *> > > > * _Ln) Line 247	C++	Symbols loaded.
 	semantic_monocular.exe!std::_LaunchPad<std::unique_ptr<std::tuple<void (__thiscall ORB_SLAM2::Viewer::*)(void),ORB_SLAM2::Viewer *>,std::default_delete<std::tuple<void (__thiscall ORB_SLAM2::Viewer::*)(void),ORB_SLAM2::Viewer *> > > >::_Go() Line 232	C++	Symbols loaded.
 	semantic_monocular.exe!std::_Pad::_Call_func(void * _Data) Line 210	C++	Symbols loaded.
 	ucrtbased.dll!invoke_thread_procedure(unsigned int(__stdcall*)(void *) procedure, void * const context) Line 92	C++	Symbols loaded.
 	ucrtbased.dll!thread_start<unsigned int (__stdcall*)(void *)>(void * const parameter) Line 115	C++	Symbols loaded.
 	kernel32.dll!BaseThreadInitThunk() + 18 bytes	Unknown	No symbols loaded.
 	[Frames below may be incorrect and/or missing, no symbols loaded for kernel32.dll]		Annotated Frame
 	ntdll.dll!RtlInitializeExceptionChain() + 99 bytes	Unknown	No symbols loaded.
 	ntdll.dll!RtlInitializeExceptionChain() + 54 bytes	Unknown	No symbols loaded.
```

**Comment by apattnaik0721013** [comment]
@paul-michalik 
I find this stack corruption is present in Original Orb-slam2. i found this issue in master branch.
So in my view this stack corruption is not related to this pull request.
can  we fix this stack corruption in separate Issue.

**Comment by paul-michalik** [comment]
Is it reproducible even on unmodified application from upstream? Please verify!

**Comment by apattnaik0721013** [comment]
@paul-michalik 
this issue can be seen in the upstream for mon_tum.exe also.

**Pull request merged**
