### PR TITLE
bugfix/33-Fix-AppVeyor-CI

### PR DESCRIPTION
**Pull request by shanmukhananda**
Changes:
- fix appveyor CI using the combination of `vcpkg export` and dropbox

I think its better we have some working CI setup for windows than none.

### CODE REVIEW

**Comment by shanmukhananda** [comment]
Refer: [Appveyor Log](https://ci.appveyor.com/project/paul-michalik/orb-slam2/build/1.0.731)

**Review by paul-michalik — COMMENTED** [review]
I agree with better something than nothing strategy, but, no, please don't do this. We are making too many assumptions:
1. Use the bootstrap, configure, build... API for appveyor too
2. Use native tools for download, unzip. Otherwise take care that these tools are installed.
3. The upload/download of binary artifacts needs to be versioned, otherwise we depend on hot air. The build needs to have a tag/id for binaries assigned. During bootstrap it checks whether that tag is present on a list of specified servers and pulls the first one. Otherwise it builds everything from scratch.

**Comment by shanmukhananda** [comment]
> Use the bootstrap, configure, build... API for appveyor too

I tried this to begin with but each script is a chain to another till `bootstrap.bat`, but `bootstrap.bat` requires vcpkg as git repo. But `VCPKG_ROOT_DIR` may not be a [git repo always](https://github.com/paul-michalik/ORB_SLAM2/blob/c2c3fa2fd3869593bc5b716c883deaf07dea82d3/scripts/windows/bootstrap.bat#L48). (i.e. in case of vcpkg export case), deviating from DRY principle is the only quick fix/hack, I could come up with.

> Use native tools for download, unzip. Otherwise take care that these tools are installed.

I assume Native tools = Powershell APIs, the problem with this idea is windows 7 do not have much powershell APIs to download and extract. Also I found using 7z reduces the total binary size just under 250MB (which includes both Release and Debug deps) Not sure if zip can achieve such high compression. Appveyor provides both `curl` and `7z` pre-installed.

> The upload/download of binary artifacts needs to be versioned

With dropbox I can [revert to older package](https://www.dropbox.com/help/security/recover-older-versions). 

Before we stop our work here, I want to leave it in a build-able and runnable state, with CI support for both platform. 

Random thoughts:
- Do `get fetch` only if `VCPKG_ROOT_DIR` is a git repo
- I dont know how to check the commit lock. Add commit lock to filename, (vcpkg export) will help?
- Even then [this](https://github.com/paul-michalik/ORB_SLAM2/blob/e390308d87282e5755536d99249b214d8466d386/scripts/windows/bootstrap.bat#L57) line might cause problems because `vcpkg.exe` is not present at all
- Given an vcpkg export archive can I still use bootstrap, configure, build scripts?

**Comment by shanmukhananda** [comment]
I guess we can have a more elegant solution when we have [vcpkg.io](https://github.com/paul-michalik/vcpkg.io) ready. Closing PR for now.

**Pull request closed without merging**
